idxs = ['Treg', 'Angiogenic_4', 'Acinar_cell_1', 'Ecm_myCAF_1', 'Arterial_1',
       'Arterial_2', 'Mesenchymal', 'Ductal_cell_A_3', 'IFNy_iCAF_1',
       'Mono_2', 'Macro_SPP1', 'Mast', 'CD4Tex', 'Detox_iCAF_2',
       'Capillary_1', 'Ductal_cell_B_4', 'Detox_iCAF_1', 'Plasma_1', 'CD4Tn',
       'Detox_iCAF_3', 'Angiogenic_3', 'TRM', 'Interferon_Epi',
       'Ductal_cell_A_5', 'cDC2', 'Wound_myCAF_2', 'Wound_myCAF_1',
       'Acinar_cell_2', 'cDC1', 'IFNy_iCAF_2', 'Follicular_B_cell',
       'Hypoxia-CAF', 'Ecm_myCAF_2', 'Ecm_myCAF_3', 'Angiogenic_2',
       'Ductal_cell_B_3', 'Macro_APOE', 'CD8Pro', 'GC_B_1', 'Ductal_cell_A_4',
       'CD8Tem_1', 'Macro_ACP5', 'Angiogenic_1', 'CD8Tem_2', 'CD4Tem_1',
       'CD8Tex', 'Ductal_cell_A_1', 'Langerhans-like', 'Endocrine_cell',
       'Basal', 'Macro_Cycing', 'Capillary_2', 'Naïve_B', 'Macro_SPP1_APOE',
       'Mono_1', 'mature_cDC', 'Venous', 'Aactivated_PCV_2', 'GC_B_2', 'Plasma_2',
       'Plasma_3', 'Th', 'TGFβ_myCAF', 'Ductal_cell_B_5', 'Ductal_cell_A_2',
       'IL_iCAF', 'pDC1', 'T_progenitors', 'Acinar_cell_3', 'Ductal_cell_B_2',
       'Macro_CREM', 'Ductal_cell_B_1', 'Macro_CXCL10', 'Aactivated_PCV_1']